### ISSUE TITLE
Incompatible licenses

### ISSUE THREAD

**Issue by mattelacchiato** [sfa-siard/Zip64File#1]
Hi,

the LICENSE.txt declares a CDDL license, but the java source files have a GPL license header. [Wikipedia](https://en.wikipedia.org/wiki/Common_Development_and_Distribution_License) says that those licences are incompatible.

It would help us a lot if the CDDL would be used for the project, otherwise we couldn't use it :-(

If you approve, I would create a pull request to change the source file headers.

**Comment by HartwigThomas** [comment]
Enter AG had published the sources before under GPL. For the SIARD project all sources are under CDDL.
I do approve. Please create the pull request.

**Comment by HartwigThomas** [comment]
The licenses have been fixed in the current release (2.1.34).
