### ISSUE TITLE
 invalid size (expected from local header/data descriptor 0 but actually found 27325 bytes)

### ISSUE THREAD

**Issue by petervalencic** [sfa-siard/Zip64File#2]
Hi,
have a zip file which I can open in windows or with winrar.
If I try to open it with Zip64File i got:

`java.util.zip.ZipException: invalid size (expected from local header/data descriptor 0 but actually found 27325 bytes)
	at ch.enterag.utils.zip.EntryInputStream.close(EntryInputStream.java:358)
	at com.in2.Unziper.main(Unziper.java:175)`

with others zip files all works well..

**Comment by HartwigThomas** [comment]
Can you give more information or a sample file?
Does it work with pkzip (zip64 is interoperable with pkzip which defines the ZIP standard, but not necessarily with winrar)?
Is the file encrypted? (zip64 does not support encryption)?
Does winrar report, which version of the ZIP standard was discovered in the file?

**Comment by petervalencic** [comment]
Please send me mail to peter.valencic@gmail.com so I can send you my zip file (I can't publish it on web (private data)).

What is strange is that I can extract a file from a zip file but get also a exception 

Source code:

        public static void main(String[] args) {
        EntryInputStream zis = null;
        BufferedOutputStream dest = null;
        try {

            String uuid = UUID.randomUUID().toString();
            System.out.println(uuid);
            int buffer = 2048;
            byte data[] = new byte[buffer];
            int count;
            Zip64File zipFile = new Zip64File(new File("c:/testiranje/attachment.zip"), true);
            List<FileEntry> entityList = zipFile.getListFileEntries();
            for (FileEntry entry : entityList) {
                if (!entry.isDirectory()) {
                    zis = zipFile.openEntryInputStream(entry.getName());
                    System.out.println("zapisujem: " + entry.getName());
                    dest = new BufferedOutputStream(new FileOutputStream("c:/testiranje/" + entry.getName()), buffer);
                    while ((count = zis.read(data, 0, buffer)) != -1) {
                        dest.write(data, 0, count);
                    }
                    dest.flush();

                }

            }
         
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            if (dest != null) {
                try {
                    dest.close();
                } catch (IOException ex) {
                    Logger.getLogger(Unziper.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (zis != null) {
                try {
                    zis.close();
                } catch (IOException ex) {
                    Logger.getLogger(Unziper.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }`

https://postimg.cc/image/pnehc5a37/

**Comment by HartwigThomas** [comment]
Could not get a sample file. Closing issue.
