### ISSUE TITLE
Wrong size in ZIP64 extended information extra field of local file header

### ISSUE THREAD

**Issue by marhop** [sfa-siard/Zip64File#5]
In the ZIP64 extended information extra field of the local file header, both uncompressed and compressed size are set to 0 even for non-empty files. This is wrong.

Proposed Solution
=================

At the least, the correct size values should be written to the ZIP64 extended information extra field, not only to the data descriptor.

Optional enhancement: Is it possible to ditch the data descriptor altogether in favor of an unambiguous use of the ZIP64 extension? (Remember to move the CRC-32 checksum from the data descriptor to the local file header if you do this!) This notion is backed by the requirement that a data descriptor "SHOULD be used only when it was not possible to seek in the output .ZIP file, e.g., when the output .ZIP file was standard output". \[[APPNOTE](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) section 4.3.9\]

Background
==========

(See example file in [this issue](https://github.com/sfa-siard/Zip64File/issues/4).)

There are at least five places in a ZIP64 file where the size of a zipped file can be recorded:

-   in the *local file header* and in the *central directory header*, if the size value fits into 32 bits (like a regular ZIP file)
-   in the *ZIP64 extended information extra field* of the local file header and of the central directory header, if the size fields in the local file header and in the central directory header are set to 0xffffffff
-   in the *data descriptor*, if bit 3 of the general purpose bit flag is set (and the size fields in the local file header are set to 0x00000000)

This is specified in \[[APPNOTE](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) sections 4.4.8 and 4.4.9\]:

> If bit 3 of the general purpose bit flag is set, these fields are set to zero in the local header and the correct values are put in the data descriptor and in the central directory. If an archive is in ZIP64 format and the value in this field is 0xFFFFFFFF, the size will be in the corresponding 8 byte ZIP64 extended information extra field.

This makes it difficult to combine a data descriptor with the ZIP64 extension because the format specification, if not even contradictory in itself, at least leaves some room for interpretation: Should the size fields be set to 0x00000000 or 0xffffffff? Should their actual values be written to the ZIP64 extended information extra field, to the data descriptor, or both?

Currently, the size fields in the local file header are set to 0xffffffff as required by ZIP64 but the actual values are stored only in the data descriptor, *not* in the ZIP64 extended information extra field.

However, depending on how a ZIP parser decides where to look for the size values it may use each of the following approaches and would in both cases be more or less in line with the ZIP file format specification, so both ways should work:

-   Look at the general purpose bit flag, see that bit 3 is set, and thus look at the size field in the data descriptor (ignoring the fact that the size field in the local file header is not set to 0x00000000). This works fine already, provided [this bug](https://github.com/sfa-siard/Zip64File/issues/4) is fixed.
-   Look at the size field in the local file header or central directory header, see that it is set to 0xffffffff, and thus look at the size field in the ZIP64 extended information extra field (ignoring the general purpose bit flag). Currently this results in 0 for the local file header and probably just blows up for the central directory header because [there is no ZIP64 extended information extra field in the central directory header](https://github.com/sfa-siard/Zip64File/issues/6).

**Comment by marhop** [comment]
Come to think of it, in case the data descriptor is absolutely required, I suppose another valid (albeit maybe unusual) approach could be to remove the ZIP64 extended information extra field from the local file header, set both size fields in the local file header to 0x00000000 and store the actual values only in the data descriptor, not in the extra field. That would as well eliminate the ambiguity described above.

I would prefer to remove the data descriptor though, but that's just a matter of personal taste. ;-)

**Comment by marhop** [comment]
(I guess your last comment should have belonged to [this issue](https://github.com/sfa-siard/Zip64File/issues/4)? Thanks for the info anyway!)

**Comment by HartwigThomas** [comment]
I understand the appnote differently.

If the general purpose flag is set (corrected now), no information about sizes must go to the local file entry header. Instead both sizes are to be set to 0 and the correct size information follows in the data descriptor after the file content as well as in the global central directory.
However, for ZIP64 files when setting the 8-byte sizes to zero, it is necessary to set the 4-byte sizes to 0xFFFFFFFF and the extended 8-byte sizes to 0.

**Comment by marhop** [comment]
Ah yes, you are right!

In order to write the correct size to the ZIP64 extended information extra field the size would have to be known when writing the local file header (which the extra field is part of). But if it *was* known when writing the local file header, then there would be no need for the data descriptor at all. So this cannot be intended by the specification.

What a confusing spec ... Anyway, your are right and I withdraw the issue! ;-)

Have a nice weekend!
