### ISSUE TITLE
Missing ZIP64 extended information extra field in central directory header

### ISSUE THREAD

**Issue by marhop** [sfa-siard/Zip64File#6]
A ZIP64 extended information extra field should be added to the central directory header, not only to the local file header. See [this issue](https://github.com/sfa-siard/Zip64File/issues/5) for background details.

**Comment by HartwigThomas** [comment]
The issue you refer to, has been closed.
A ZIP64 extended information field IS added to the central directory header.
Please indicate, where it is not and then reopen this issue.

**Comment by marhop** [comment]
OK, I checked this again (v2.1.34): Apparently, the extra field is added to the central directory header only if one of the regular fields gets too small. Example:

* Zipping a small file (< 4 GB): no extra field in central directory header because it's not necessary.
* Zipping a large file (> 4 GB): extra field in central directory header because the regular "uncompressed size" field is too small for values greater than 4 GB.

Alright then!

PS: I guess what made me wonder is that the *local* file header (unlike the central directory header) always contains a ZIP64 extended information extra field, even for small files. But that's presumably due to the use of the data descriptor again. ;-)
