### ISSUE TITLE
Switch to java.util.zip or Apache Commons Compress?

### ISSUE THREAD

**Issue by marhop** [sfa-siard/Zip64File#7]
Hi,

No offense meant, but is there a specific reason SIARD Suite still develops its own ZIP64 library although [java.util.zip has been supporting the ZIP64 extension for a while now](https://web.archive.org/web/20110530122909/https://blogs.oracle.com/xuemingshen/entry/zip64_support_for_4g_zipfile), another option being [Apache Commons Compress](http://commons.apache.org/proper/commons-compress/zip.html) which, I think, is also used by [database preservation toolkit](https://github.com/keeps/db-preservation-toolkit)?

No need to maintain it yourself ;-)

Best regards,
Martin

**Comment by HartwigThomas** [comment]
For the moment, I consider the changes to SIARD2 too grave. The java.util.zip API is not suited for SIARD. One of the problems is accessing the metadata file in a LARGE SIARD file really fast.
